### ISSUE TITLE
Error: Module build failed... server/express.js: Unexpected token (52:10)

### ISSUE THREAD

**Issue by Mazuco** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#1]
Appear this error when lauch the command:

yarn start or yarn development

Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/mz2/teste/server/express.js: Unexpected token (52:10)

`const markup = ReactDOMServer.renderToString(
sheets.collect(
<StaticRouter location={req.url} context={context}>
^
<ThemeProvider theme={theme}>
<MainRouter />
</ThemeProvider>`

**Comment by shamahoque** [comment]
This error is not thrown if you are running the code directly from this repository.
Maybe an extra character was copied, if you copy-pasted this code from the book. It is difficult to assess this issue without access to the code you are running.

**Comment by Mazuco** [comment]
the code is equal in this repository, I used wget command for get this code

**Comment by Mazuco** [comment]
ok
