### ISSUE TITLE
SOLVED_____________chapter 7 - {"error":"Error: Material-UI: capitalize(string) expects a string argument."}

### ISSUE THREAD

**Issue by adrian-gvr** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#105]

**Comment by adrian-gvr** [comment]
/client/core/Menu.js
In place of this code:
          {/* <Button color={isActive(history, "/cart")}> */}

i inserted this other code:
         <Button style={isActive(history, "/cart")}>

**Comment by packt-pradeeps** [comment]
Thank you for sharing this improvement
