### ISSUE TITLE
ERROR in multi ./server/server.js

### ISSUE THREAD

**Issue by Mazuco** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#2]
Hi, I'm test the Chapter 3 - but it apperar this error when I test the server:

`
mz2@mz2:~/jwtapp$ yarn development
yarn run v1.22.4
$ nodemon
[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): server
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `webpack --mode=development --config webpack.config.server.js && node ./dist/server.generated.js`
Hash: 1e73917036ff8f9ada48
Version: webpack 4.43.0
Time: 33ms
Built at: 05/11/2020 9:15:56 PM
              Asset      Size  Chunks             Chunk Names
server.generated.js  3.98 KiB    main  [emitted]  main
Entrypoint main = server.generated.js
[0] multi ./server/server.js 28 bytes {main} [built]

ERROR in multi ./server/server.js
Module not found: Error: Can't resolve '/home/mz2/jwtapp/server/server.js' in '/home/mz2/jwtapp'
 @ multi ./server/server.js main[0]
[nodemon] process failed, unhandled exit code (2)
[nodemon] 
[nodemon] Either the command has a syntax error,
[nodemon] or it is exiting with reserved code 2.
[nodemon] 
[nodemon] To keep nodemon running even after a code 2,
[nodemon] add this to the end of your command: || exit 1
[nodemon] 
[nodemon] Read more here: https://git.io/fNOAG
[nodemon] 
[nodemon] nodemon will stop now so that you can fix the command.
[nodemon] 
[nodemon] Error
    at Bus.<anonymous> (/home/mz2/jwtapp/node_modules/nodemon/lib/nodemon.js:156:25)
    at Bus.emit (events.js:323:22)
    at ChildProcess.<anonymous> (/home/mz2/jwtapp/node_modules/nodemon/lib/monitor/run.js:187:11)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Done in 0.44s.

`
How to fix this error?

**Comment by shamahoque** [comment]
It looks like the server.js file is not in the `jwtapp/server/` folder as expected when you are running the command. Make sure you are in the correct folder.

**Comment by Mazuco** [comment]
ok
