### ISSUE TITLE
expressJWT - algorithms should be set

### ISSUE THREAD

**Issue by rfinkley** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#28]
When I got to the 'Checking the standalone backend' section, I ran `npm run development` and received the following error:

`Error: algorithms should be set
    at module.exports (D:\react\mern-skeleton\node_modules\express-jwt\lib\index.js:22:34)
    at eval (webpack:///./server/controllers/auth.controller.js?:56:73)`

After googling, I found a suggestion for adding `algorithms: ['RS256']` to the `requireSignin` declaration and it solved the error.

`const requireSignin = expressJwt({
  secret: config.jwtSecret,
  userProperty: 'auth',
  algorithms: ['RS256'],
});`

I don't know that RS256 is the correct algorithm. I was wondering if I failed to include something from the example.

**Comment by shamahoque** [comment]
You didn't miss anything from the example. This `algorithms` requirement was added in a later version of the expressJWT package. The book example uses a previous version which didn't have this requirement. 

RS256 seems to be a standard option for basic login authentication. It will get the job done for these examples.

**Comment by rfinkley** [comment]
In testing the API routes, I found that /auth/signin won't work with RS256 but it does work with HS256. Thanks for your help. I was able to get through all the API Routes testing. I'm going to close this issue. Will keep you posted if anything else pops up. Learning a lot, thanks again.
