### ISSUE TITLE
MERN marketplace, adding quantity option to product page

### ISSUE THREAD

**Issue by fullstackmepapi** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#36]
Having trouble adding a quantity selector to the product page and making it reflect accurately in the cart. 
Im not sure if this is possible to do given the current structure of the project. Any advice?

**Comment by shamahoque** [comment]
Should be possible with some modifications. 
You will have to pass the quantity collected from the selector to the `addItem` [function in cart-helper.js](https://github.com/shamahoque/mern-marketplace/blob/second-edition/client/cart/cart-helper.js#L10). 
Currently, this function sets the quantity statically to 1 when a user clicks on [AddToCart](https://github.com/shamahoque/mern-marketplace/blob/second-edition/client/cart/AddToCart.js) for a product.
