### ISSUE TITLE
webpack should resolve .jsx files

### ISSUE THREAD

**Issue by nguyenxndaidev** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#4]
To be friendly with IDE, such as IntelliJ in my case, react files should be renamed to `.jsx` and webpack should resolve `.js` and `.jsx` extensions.

```
const config = {
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
        resolve: {
          extensions: ['.js', '.jsx']
        }
      }
    ]
  }
}
```

or

```
const config = {
  resolve: {
    extensions: ['.js', '.jsx']
  }
}
```

**Comment by sarvesh-packt** [comment]
Hi, 

Can you please elaborate and give more details about your issue.

**Comment by shamahoque** [comment]
This is a good suggestion for readers looking to work with .jsx files.
