### ISSUE TITLE
package.json script on Windows

### ISSUE THREAD

**Issue by nguyenxndaidev** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#5]
I didn't test the script `"start": "NODE_ENV=production node ./dist/server.generated.js"` on Linux or Mac. But script on Windows should be `"start": "SET NODE_ENV=production && node ./dist/server.generated.js"`

**Comment by sarvesh-packt** [comment]
Hi, 

Can you please elaborate and give more details about your issue.

**Comment by shamahoque** [comment]
This is more of an OS-specific enhancement tip that will be helpful to some readers.

Thank you, Nguyen.
