### ISSUE TITLE
Helmet & webpack-dev-Middleware

### ISSUE THREAD

**Issue by david238** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#53]
At this time, I am trying this codes, helmet is forcing https instead of http and webpack-dev-Middleware was not writing the bundle.js file under /dist, due to missing argument, writeToDisk: true, by default its false.

**Comment by shruthis-shetty** [comment]
@david238 Your issue got solved or not?

**Comment by david238** [comment]
> @david238 Your issue got solved or not?

It was. thank you!
