### ISSUE TITLE
Rendering a home page view 

### ISSUE THREAD

**Issue by EnriqueFarfanAlvarez** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#54]
Hi!, I have a problem when I try to Rendering the home page view. The problem occurs when i go to localhost:3000, I only see blank page and components are not rendered :(. When i start the server all its ok, but i don't understand why happend this. I checked that my code is the same that the code in github. If you need more information to help me I am attentive to your comments. Thx! 

 

![image](https://user-images.githubusercontent.com/79018714/107856729-ed99b780-6e08-11eb-9f0e-f558fb6c6c0b.png)

**Comment by EnriqueFarfanAlvarez** [comment]
I add some aditional information 

![image](https://user-images.githubusercontent.com/79018714/107859628-686ace80-6e19-11eb-9ba0-ce5201826ccf.png)

**Comment by EnriqueFarfanAlvarez** [comment]
I fixed it by removing the "helmet" npm package. I don't understand why, but now this works fine. Anyone can explain to me what happened?. 

edit: This solution only work with firefox, but the problem still continue in google chrome :(

**Comment by shruthis-shetty** [comment]
Thanks for the solution @HashOil1.

**Comment by panduananto** [comment]
i got it working with helmet by setting it up like this:

```
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        ...helmet.contentSecurityPolicy.getDefaultDirectives(),
        'script-src': ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
      },
    },
  })
);
```

**Comment by EnriqueFarfanAlvarez** [comment]
> i got it working with helmet by setting it up like this:
> 
> ```
> app.use(
>   helmet({
>     contentSecurityPolicy: {
>       directives: {
>         ...helmet.contentSecurityPolicy.getDefaultDirectives(),
>         'script-src': ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
>       },
>     },
>   })
> );
> ```

Thank you very much!, you helped me a lot with your answer.

**Comment by oriankeith002** [comment]
> i got it working with helmet by setting it up like this:
> 
> ```
> app.use(
>   helmet({
>     contentSecurityPolicy: {
>       directives: {
>         ...helmet.contentSecurityPolicy.getDefaultDirectives(),
>         'script-src': ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
>       },
>     },
>   })
> );
> ```

Thanks for your solution, it was very helpful
