### ISSUE TITLE
Webpack Eval() error

### ISSUE THREAD

**Issue by cdevjarrell** [PacktPublishing/Full-Stack-React-Projects-Second-Edition#73]
When trying to run the project, I continuously run into this issue in the console.

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Object../node_modules/webpack-hot-middleware/client.js?reload=true (bundle.js:2968)
    at __webpack_require__ (bundle.js:3029)
    at bundle.js:4098
    at bundle.js:4101

Is there a solution? This seems to be a common webpack issue that I can't figure out.

**Comment by EnriqueFarfanAlvarez** [comment]
Hello! I think this could help https://github.com/PacktPublishing/Full-Stack-React-Projects-Second-Edition/issues/54

**Comment by nithikpackt** [comment]
Thank you @HashOil1 for mentioning the solution
